apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: alexb-jenkins
  name: jenkins-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]